FROM myjdk-env:1.0

COPY target/rentalCarBooking-server-0.0.1-SNAPSHOT.jar /data/apps/rentalCarBooking-server-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/data/apps/rentalCarBooking-server-0.0.1-SNAPSHOT.jar"]